using System.Collections.Generic;
using Microsoft.CodeAnalysis;
using System.Linq;

namespace Lwx.Archetype.MicroService.Generator.Processors;

internal class LwxSwaggerTypeProcessor(
    FoundAttribute attr,
    SourceProductionContext ctx,
    Compilation compilation
)
{
    public void Execute()
    {
        // enforce file path and namespace matching for swagger marker classes
        GeneratorHelpers.ValidateFilePathMatchesNamespace(attr.TargetSymbol, ctx);
        // Check if Swashbuckle is available
        var openApiInfoType = compilation.GetTypeByMetadataName("Microsoft.OpenApi.Models.OpenApiInfo");
        if (openApiInfoType == null)
        {
            ctx.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor(
                    "LWX003",
                    "Missing Swashbuckle package",
                    "LwxSwagger requires the Swashbuckle.AspNetCore package. Install it using: dotnet add package Swashbuckle.AspNetCore",
                    "Dependencies",
                    DiagnosticSeverity.Error,
                    isEnabledByDefault: true),
                attr.Location));
            return;
        }

        var name = GeneratorHelpers.SafeIdentifier(attr.TargetSymbol.Name);
        var ns = attr.TargetSymbol.ContainingNamespace?.ToDisplayString() ?? "Generated";

        string title = null;
        string description = null;
        string version = null;
        string publishLiteral = "Lwx.Archetype.MicroService.Atributes.LwxStage.None";

        if (attr.AttributeData != null)
        {
            var m1 = attr.AttributeData.NamedArguments.FirstOrDefault(kv => kv.Key == "Title");
            if (!m1.Equals(default(KeyValuePair<string, TypedConstant>)) && m1.Value.Value is string s1)
            {
                title = s1;
            }
            var m2 = attr.AttributeData.NamedArguments.FirstOrDefault(kv => kv.Key == "Description");
            if (!m2.Equals(default(KeyValuePair<string, TypedConstant>)) && m2.Value.Value is string s2)
            {
                description = s2;
            }
            var m3 = attr.AttributeData.NamedArguments.FirstOrDefault(kv => kv.Key == "Version");
            if (!m3.Equals(default(KeyValuePair<string, TypedConstant>)) && m3.Value.Value is string s3)
            {
                version = s3;
            }

            var m4 = attr.AttributeData.NamedArguments.FirstOrDefault(kv => kv.Key == "Publish");
            if (!m4.Equals(default(KeyValuePair<string, TypedConstant>)) && m4.Value.Value != null)
            {
                var raw = m4.Value.Value;
                if (raw is int iv)
                {
                    publishLiteral = iv switch
                    {
                        1 => "Lwx.Archetype.MicroService.Atributes.LwxStage.Development",
                        2 => "Lwx.Archetype.MicroService.Atributes.LwxStage.Production",
                        _ => "Lwx.Archetype.MicroService.Atributes.LwxStage.None"
                    };
                }
                else
                {
                    var tmp = m4.Value.Value.ToString() ?? "Lwx.Archetype.MicroService.Atributes.LwxStage.None";
                    publishLiteral = tmp.Contains('.') ? tmp : ("Lwx.Archetype.MicroService." + tmp);
                }
            }
        }

        var configureSource = $$"""
            // <auto-generated/>
            using Lwx.Archetype.MicroService.Atributes;

            namespace {{ns}}
            {
                public static partial class {{name}}
                {
                    // Swagger configuration is now handled in LwxConfigure extensions
                }
            }
            """;

        GeneratorHelpers.AddGeneratedFile(ctx, $"LwxSwagger_{name}.Configure.g.cs", configureSource);
    }
}
