using Microsoft.CodeAnalysis;

namespace Lwx.Archetype.MicroService.Generator.Processors;

internal class LwxServiceBusProducerTypeProcessor(
    FoundAttribute attr,
    SourceProductionContext ctx,
    Compilation _
)
{
    public void Execute()
    {
        // enforce file path and namespace matching for classes marked with Lwx attributes
        GeneratorHelpers.ValidateFilePathMatchesNamespace(attr.TargetSymbol, ctx);
        var name = GeneratorHelpers.SafeIdentifier(attr.TargetSymbol.Name);
        var ns = attr.TargetSymbol.ContainingNamespace?.ToDisplayString() ?? "Generated";
        var source = $$"""
            // <auto-generated/>
            namespace {{ns}}
            {
                public static partial class LwxServiceBusProducer_Generated_{{name}}
                {
                    // Detected attribute: {{attr.AttributeName}} on {{attr.TargetSymbol.Kind}} {{attr.TargetSymbol.Name}}
                }
            }
            """;

        GeneratorHelpers.AddGeneratedFile(ctx, $"LwxServiceBusProducer_{name}.g.cs", source);
    }
}
