using System.Diagnostics.CodeAnalysis;
using Microsoft.CodeAnalysis;

namespace Lwx.Archetype.MicroService.Generator.Processors;

internal class LwxWorkerTypeProcessor(
    FoundAttribute attr,
    SourceProductionContext ctx,
    Compilation _
)
{
    public void Execute()
    {
        var name = GeneratorHelpers.SafeIdentifier(attr.TargetSymbol.Name);
        var ns = attr.TargetSymbol.ContainingNamespace?.ToDisplayString() ?? "Generated";
        var source = $$"""
            // <auto-generated/>
            using System;
            namespace {{ns}}
            {
                public static partial class LwxWorker_Generated_{{name}}
                {
                    // Detected attribute: {{attr.AttributeName}} on {{attr.TargetSymbol.Kind}} {{attr.TargetSymbol.Name}}
                }
            }
            """;

        GeneratorHelpers.AddGeneratedFile(ctx, $"LwxWorker_{name}.g.cs", source);
    }
}
