// <auto-generated/>
using System;
using System.Linq;
using System.Reflection;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Lwx.Archetype.MicroService.Atributes;

namespace Lwx.Archetype.MicroService.Atributes
{
    /// <summary>
    /// Provides extension methods for validating Lwx endpoint configuration in ASP.NET Core applications.
    /// </summary>
    public static class LwxEndpointExtensions
    {
        /// <summary>
        /// Configures Lwx services, including Swagger if enabled.
        /// </summary>
        /// <param name="builder">The web application builder.</param>
        public static void LwxConfigure(this WebApplicationBuilder builder)
        {
            // Configure Swagger if available
            var assembly = Assembly.GetExecutingAssembly();
            var swaggerType = assembly.GetTypes().FirstOrDefault(t => t.Name == "Swagger" && t.IsClass && t.IsAbstract && t.IsSealed); // static class
            if (swaggerType != null)
            {
                var method = swaggerType.GetMethod("Configure", new[] { typeof(WebApplicationBuilder) });
                method?.Invoke(null, new object[] { builder });
            }
        }

        /// <summary>
        /// Registers validation to ensure all registered endpoints in the application are mapped through the Lwx mechanism.
        /// Also configures Swagger UI if enabled.
        /// </summary>
        /// <param name="app">The web application instance.</param>
        /// <remarks>
        /// <para>This validation excludes common infrastructure endpoints like health checks,
        /// readiness probes, and Swagger UI.</para>
        /// <para>The validation is performed asynchronously when the application starts to ensure
        /// all endpoint registrations are complete.</para>
        /// <para>Call this method at application startup after configuring all services and endpoints:</para>
        /// <code>
        /// var app = builder.Build();
        /// // Configure endpoints...
        /// app.LwxConfigure();
        /// app.Run();
        /// </code>
        /// </remarks>
        public static void LwxConfigure(this WebApplication app)
        {
            // Configure Swagger UI if available
            var assembly = Assembly.GetExecutingAssembly();
            var swaggerType = assembly.GetTypes().FirstOrDefault(t => t.Name == "Swagger" && t.IsClass && t.IsAbstract && t.IsSealed); // static class
            if (swaggerType != null)
            {
                var method = swaggerType.GetMethod("Configure", new[] { typeof(WebApplication).Assembly.GetType("Microsoft.AspNetCore.Builder.IApplicationBuilder") ?? typeof(IApplicationBuilder) });
                method?.Invoke(null, new object[] { app });
            }

            var lifetime = app.Services.GetRequiredService<IHostApplicationLifetime>();
            lifetime.ApplicationStarted.Register(() =>
            {
                ValidateLwxEndpoints(app);
            });
        }

        private static void ValidateLwxEndpoints(WebApplication app)
        {
            var exceptions = new[] { "health", "ready", "swagger" };
            var endpointDataSources = app.Services.GetServices<EndpointDataSource>();
            foreach (var dataSource in endpointDataSources)
            {
                foreach (var endpoint in dataSource.Endpoints)
                {
                    if (endpoint.Metadata.GetMetadata<LwxEndpointMetadata>() == null)
                    {
                        var name = endpoint.DisplayName ?? endpoint.ToString();
                        if (!exceptions.Any(e => name.Contains(e, StringComparison.OrdinalIgnoreCase)))
                        {
                            throw new InvalidOperationException($"Endpoint {name} is not mapped by Lwx mechanism");
                        }
                    }
                }
            }
        }
    }
}