using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.Hosting;
using MyCompany.MyUnit.Worker001.Endpoints;
using MyCompany.MyUnit.Worker001.Endpoints.ExampleProc;
using Lwx.Archetype.MicroService.Atributes;

var builder = WebApplication.CreateBuilder(args);

// Configure Lwx services, including Swagger if enabled
builder.LwxConfigure();

var app = builder.Build();

// Configure Lwx app, including Swagger UI if enabled
app.LwxConfigure();

// Map all endpoints generated by Lwx source generator
EndpointProc01Start.Configure(app);
EndpointAbcCde.Configure(app);
EndpointProc01MakeAbc.Configure(app);
EndpointExampleProcStart.Configure(app);
EndpointExampleProcFunc001.Configure(app);
EndpointExampleProcFunc002.Configure(app);
EndpointExampleProcFinish.Configure(app);

app.Run();
