using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.Hosting;
using MyCompany.MyUnit.Worker001.Endpoints;
using Lwx.Archetype.MicroService.Atributes;

var builder = WebApplication.CreateBuilder(args);

// Configure Swagger if enabled
Swagger.ConfigureSwagger(builder.Services, builder.Environment);

var app = builder.Build();

// Configure Swagger UI if in development
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

// Map all endpoints generated by Lwx source generator
EndpointProc01Start.Configure(app);
EndpointAbcCde.Configure(app);
EndpointProc01MakeAbc.Configure(app);

// Validate that all endpoints are mapped by Lwx mechanism
app.LwxConfigure();

app.Run();
