// <auto-generated/>
namespace Lwx.Builders.MicroService.Atributes
{
    /// <summary>
    /// Specifies the implementation strategy for DTO properties.
    /// </summary>
    public enum DtoType
    {
        /// <summary>
        /// Properties are implemented using private backing fields.
        /// </summary>
        Normal,

        /// <summary>
        /// Properties are implemented using a dictionary for dynamic storage.
        /// </summary>
        Dictionary
    }
}