// <auto-generated/>
using System;

namespace Lwx.Builders.MicroService.Atributtes
{
    /// <summary>
    /// Marks a constructor parameter as sourced from configuration. The value will be looked up
    /// inside the worker's configuration section and bound to a generated POCO when the worker
    /// factory is created by the source generator.
    /// </summary>
    [AttributeUsage(AttributeTargets.Parameter, AllowMultiple = false)]
    public sealed class FromConfigAttribute : Attribute
    {
        public string Name { get; }

        public FromConfigAttribute(string name)
        {
            Name = name ?? string.Empty;
        }
    }
}
