// <auto-generated/>
using System;
using System.Threading;
using System.Threading.Tasks;

namespace Lwx.Builders.MicroService.Atributtes
{
    /// <summary>
    /// Handles errors at the provider/worker level (connections, topology, background failures).
    /// Implement this interface to define how the system should respond to infrastructure-level
    /// errors such as connection losses or configuration issues.
    /// </summary>
    public interface ILwxProviderErrorPolicy
    {
        /// <summary>
        /// Handles a provider-level error.
        /// </summary>
        /// <param name="ex">The exception that occurred at the provider level.</param>
        /// <param name="ct">Cancellation token.</param>
        /// <returns>A task that completes when error handling is done.</returns>
        Task HandleProviderErrorAsync(Exception ex, CancellationToken ct = default);
    }
}
