// <auto-generated/>
using System;
using System.Threading;
using System.Threading.Tasks;

namespace Lwx.Builders.MicroService.Atributtes
{
    /// <summary>
    /// Handles errors thrown by the message handler (message-processing errors).
    /// Implement this interface to define custom error handling strategies such as
    /// retry, dead-letter, or logging.
    /// </summary>
    public interface ILwxErrorPolicy
    {
        /// <summary>
        /// Handles an error that occurred while processing a message.
        /// </summary>
        /// <param name="msg">The message that was being processed when the error occurred.</param>
        /// <param name="ex">The exception that was thrown.</param>
        /// <param name="ct">Cancellation token.</param>
        /// <returns>A task that completes when error handling is done.</returns>
        Task HandleErrorAsync(ILwxQueueMessage msg, Exception ex, CancellationToken ct = default);
    }
}
