// <auto-generated/>
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;

namespace Lwx.Builders.MicroService.Atributtes
{
    /// <summary>
    /// Represents a queue provider that can be used to receive messages from a message queue.
    /// Implement this interface to integrate with different queue technologies (Azure Service Bus,
    /// RabbitMQ, AWS SQS, in-memory channels, etc.).
    /// </summary>
    public interface ILwxQueueProvider
    {
        /// <summary>
        /// Human-friendly name for diagnostics and logging.
        /// </summary>
        string Name { get; }

        /// <summary>
        /// Called by runtime/generator wiring to provide configuration for the named section.
        /// Example: sectionName="MyQueueA" corresponds to appsettings: "Queues:MyQueueA:{...}"
        /// </summary>
        /// <param name="configuration">The application configuration.</param>
        /// <param name="sectionName">The named section for this queue provider.</param>
        void Configure(IConfiguration configuration, string sectionName);

        /// <summary>
        /// Sets the provider-level error policy for connection and worker errors.
        /// </summary>
        /// <param name="policy">The policy to handle provider-level errors.</param>
        void SetProviderErrorPolicy(ILwxProviderErrorPolicy policy);

        /// <summary>
        /// Starts the worker that reads messages and invokes the handler.
        /// </summary>
        /// <param name="handler">The handler function to invoke for each message.</param>
        /// <param name="concurrency">Number of concurrent message processors.</param>
        /// <param name="ct">Cancellation token for graceful shutdown.</param>
        /// <returns>A task that completes when the provider is started.</returns>
        Task StartAsync(Func<ILwxQueueMessage, CancellationToken, Task> handler, int concurrency, CancellationToken ct);

        /// <summary>
        /// Stops the worker gracefully.
        /// </summary>
        /// <param name="ct">Cancellation token for graceful shutdown.</param>
        /// <returns>A task that completes when the provider is stopped.</returns>
        Task StopAsync(CancellationToken ct);
    }
}
