// <auto-generated/>
#nullable enable
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Lwx.Builders.MicroService.Atributtes
{
    /// <summary>
    /// Represents a message received from a queue. Provides access to message properties
    /// and lifecycle methods (complete, abandon, dead-letter).
    /// </summary>
    public interface ILwxQueueMessage
    {
        /// <summary>
        /// Unique identifier for the message.
        /// </summary>
        string MessageId { get; }

        /// <summary>
        /// The raw message payload as bytes.
        /// </summary>
        ReadOnlyMemory<byte> Payload { get; }

        /// <summary>
        /// Message headers/properties as key-value pairs.
        /// </summary>
        IReadOnlyDictionary<string, string> Headers { get; }

        /// <summary>
        /// Timestamp when the message was enqueued.
        /// </summary>
        DateTimeOffset EnqueuedAt { get; }

        /// <summary>
        /// Marks the message as successfully processed.
        /// </summary>
        /// <param name="ct">Cancellation token.</param>
        /// <returns>A ValueTask that completes when the message is acknowledged.</returns>
        ValueTask CompleteAsync(CancellationToken ct = default);

        /// <summary>
        /// Abandons the message, making it available for reprocessing.
        /// </summary>
        /// <param name="reason">Optional reason for abandoning.</param>
        /// <param name="ct">Cancellation token.</param>
        /// <returns>A ValueTask that completes when the message is abandoned.</returns>
        ValueTask AbandonAsync(string? reason = null, CancellationToken ct = default);

        /// <summary>
        /// Moves the message to the dead-letter queue.
        /// </summary>
        /// <param name="reason">Optional reason for dead-lettering.</param>
        /// <param name="ct">Cancellation token.</param>
        /// <returns>A ValueTask that completes when the message is dead-lettered.</returns>
        ValueTask DeadLetterAsync(string? reason = null, CancellationToken ct = default);
    }
}
