// <auto-generated/>
using System;

namespace Lwx.Builders.MicroService.Atributes
{
    /// <summary>
    /// Marks a property or field in a DTO class to be ignored during generation.
    /// This attribute overrides the default behavior that forbids properties without [LwxDtoProperty].
    /// </summary>
    /// <remarks>
    /// <para>Use this attribute on properties or fields that should not be processed by the DTO generator.</para>
    /// <para>Example usage:</para>
    /// <code>
    /// [LwxDto]
    /// public class MyDto
    /// {
    ///     [LwxDtoIgnore]
    ///     public string IgnoredProperty { get; set; }
    /// }
    /// </code>
    /// </remarks>
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field, AllowMultiple = false)]
    public class LwxDtoIgnoreAttribute : Attribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LwxDtoIgnoreAttribute"/> class.
        /// </summary>
        public LwxDtoIgnoreAttribute() { }
    }
}