// <auto-generated/>
using System;
using System.Threading;
using System.Threading.Tasks;

namespace Lwx.Builders.MicroService.Atributtes
{
    /// <summary>
    /// Default error policy for message processing errors.
    /// Dead-letters the message on exception.
    /// </summary>
    public class LwxDefaultErrorPolicy : ILwxErrorPolicy
    {
        /// <summary>
        /// Gets the singleton instance of the default error policy.
        /// </summary>
        public static LwxDefaultErrorPolicy Instance { get; } = new();

        /// <inheritdoc/>
        public async Task HandleErrorAsync(ILwxQueueMessage msg, Exception ex, CancellationToken ct = default)
        {
            // Default behavior: dead-letter the message with the exception message as reason
            await msg.DeadLetterAsync(ex.Message, ct);
        }
    }
}
