// <auto-generated/>
using System;
using System.Threading;
using System.Threading.Tasks;

namespace Lwx.Builders.MicroService.Atributtes
{
    /// <summary>
    /// Default error policy for provider-level errors.
    /// Logs the error and continues (fail-open for resilience).
    /// </summary>
    public class LwxDefaultProviderErrorPolicy : ILwxProviderErrorPolicy
    {
        /// <summary>
        /// Gets the singleton instance of the default provider error policy.
        /// </summary>
        public static LwxDefaultProviderErrorPolicy Instance { get; } = new();

        /// <inheritdoc/>
        public Task HandleProviderErrorAsync(Exception ex, CancellationToken ct = default)
        {
            // Default behavior: log to console and continue
            // In production, this would typically use ILogger
            Console.Error.WriteLine($"[LwxQueueProvider] Provider error: {ex.Message}");
            return Task.CompletedTask;
        }
    }
}
