// <auto-generated/>
using System;

namespace Lwx.Builders.MicroService.Atributtes
{
    /// <summary>
    /// Marks a class as an Lwx endpoint, enabling automatic generation of ASP.NET Core endpoint mappings.
    /// This attribute is used by the Lwx source generator to create minimal API routes and configure
    /// endpoint behavior based on the specified properties.
    /// </summary>
    /// <remarks>
    /// <para>The endpoint class must contain an <c>Execute</c> method that will be mapped to the specified URI.</para>
    /// <para>Example usage:</para>
    /// <code>
    /// public static class GetUsersEndpoint
    /// {
    ///     [LwxEndpoint("GET /api/users")]
    ///     public static async Task Execute(HttpContext context)
    ///     {
    ///         // Endpoint implementation
    ///     }
    /// }
    /// </code>
    /// </remarks>
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
    public class LwxEndpointAttribute : Attribute
    {
        /// <summary>
        /// Gets or sets the URI pattern for the endpoint, including HTTP method.
        /// Format: "METHOD /path" (e.g., "GET /api/users", "POST /api/users").
        /// </summary>
        public string Uri { get; set; }

        /// <summary>
        /// Gets or sets the authorization policy name to apply to this endpoint.
        /// </summary>
        public string SecurityProfile { get; set; }

        /// <summary>
        /// Gets or sets a short summary of the endpoint's purpose, used for API documentation.
        /// </summary>
        public string Summary { get; set; }

        /// <summary>
        /// Gets or sets a detailed description of the endpoint's behavior.
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets the deployment stage(s) where this endpoint should be active.
        /// Defaults to <see cref="LwxStage.None"/>, meaning the endpoint is not mapped.
        /// </summary>
        public LwxStage Publish { get; set; } = LwxStage.None;

        /// <summary>
        /// Optional: provide a justification when an endpoint class name does not match the
        /// generator's expected naming convention. When present, the generator will accept
        /// the exception and skip the naming diagnostic (LWX001).
        /// </summary>
        public string NamingExceptionJustification { get; set; }

        /// <summary>
        /// Optional: specifies the concrete type to use for request body deserialization.
        /// When set, the endpoint will deserialize the HTTP request body to this type.
        /// Required when used with [LwxMessageSource] to specify the ILwxQueueMessage implementation.
        /// </summary>
        public Type ReqBodyType { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="LwxEndpointAttribute"/> class.
        /// </summary>
        public LwxEndpointAttribute() { }

        /// <summary>
        /// Initializes a new instance of the <see cref="LwxEndpointAttribute"/> class with the specified URI.
        /// </summary>
        /// <param name="uri">The URI pattern for the endpoint.</param>
        public LwxEndpointAttribute(string uri)
        {
            Uri = uri;
        }
    }
}