// <auto-generated/>
using System;

namespace Lwx.Builders.MicroService.Atributtes
{
    /// <summary>
    /// Marks a class as an Azure Event Hubs consumer, enabling automatic
    /// registration of event processing handlers for Event Hubs.
    /// </summary>
    /// <remarks>
    /// <para>The consumer class should implement methods to process events
    /// from Azure Event Hubs.</para>
    /// <para>The source generator will create the necessary Azure Event Hubs client
    /// registrations and event processing infrastructure.</para>
    /// <para>Example usage:</para>
    /// <code>
    /// [LwxEventHubConsumer]
    /// public class TelemetryProcessor
    /// {
    ///     public static async Task ProcessEventAsync(TelemetryEvent telemetry)
    ///     {
    ///         // Event processing logic
    ///     }
    /// }
    /// </code>
    /// </remarks>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
    public class LwxEventHubConsumerAttribute : Attribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LwxEventHubConsumerAttribute"/> class.
        /// </summary>
        public LwxEventHubConsumerAttribute() { }
    }
}