// <auto-generated/>
namespace Lwx.Builders.MicroService.Atributtes
{
    /// <summary>
    /// Metadata marker class used to identify endpoints that are managed by the Lwx framework.
    /// This class is attached to endpoint metadata to enable validation and tracking
    /// of Lwx-generated endpoints in the application.
    /// </summary>
    /// <remarks>
    /// <para>This metadata is automatically added to endpoints created by the Lwx source generator
    /// and is used by the generated Service helper methods (for example `Service.Configure` or
    /// `Service.LwxConfigure`) to validate that all endpoints in the application are properly
    /// mapped through the Lwx mechanism.</para>
    /// </remarks>
    public class LwxEndpointMetadata { }
}