// <auto-generated/>
#nullable enable
using System;

namespace Lwx.Builders.MicroService.Atributtes
{
    /// <summary>
    /// Marks a class as a message handler that processes messages from a queue.
    /// The source generator will create the necessary hosted service registrations
    /// and wiring for the message handler to receive and process messages.
    /// </summary>
    /// <remarks>
    /// <para>The handler class must contain a static <c>Execute</c> method that takes an
    /// <see cref="ILwxQueueMessage"/> parameter.</para>
    /// <para>Example usage:</para>
    /// <code>
    /// [LwxMessageHandler(
    ///     Uri = "POST /receive-message",
    ///     Stage = LwxStage.All,
    ///     QueueProvider = typeof(MyQueueProvider),
    ///     QueueConfigSection = "MyQueue",
    ///     QueueReaders = 2
    /// )]
    /// public partial class MessageHandlerReceiveMessage
    /// {
    ///     public static Task Execute(ILwxQueueMessage msg) { /* ... */ }
    /// }
    /// </code>
    /// </remarks>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
    public class LwxMessageHandlerAttribute : Attribute
    {
        /// <summary>
        /// Gets or sets the URI pattern for the optional HTTP endpoint, including HTTP method.
        /// Format: "METHOD /path" (e.g., "POST /receive-message").
        /// When set, messages can also be pushed via HTTP in addition to queue processing.
        /// </summary>
        public string Uri { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the deployment stage(s) where this handler should be active.
        /// Defaults to <see cref="LwxStage.None"/>, meaning the handler is not active.
        /// </summary>
        public LwxStage Stage { get; set; } = LwxStage.None;

        /// <summary>
        /// Gets or sets the type of the queue provider that implements <see cref="ILwxQueueProvider"/>.
        /// </summary>
        public Type? QueueProvider { get; set; }

        /// <summary>
        /// Gets or sets the configuration section name for the queue provider.
        /// This corresponds to the "Queues:{SectionName}" path in appsettings.json.
        /// </summary>
        public string QueueConfigSection { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the number of concurrent readers/processors for the queue.
        /// Defaults to 2. Can be overridden by the provider's configuration.
        /// </summary>
        public int QueueReaders { get; set; } = 2;

        /// <summary>
        /// Gets or sets the type of the handler error policy that implements <see cref="ILwxErrorPolicy"/>.
        /// Defaults to <see cref="LwxDefaultErrorPolicy"/> which dead-letters messages on error.
        /// </summary>
        public Type? HandlerErrorPolicy { get; set; }

        /// <summary>
        /// Gets or sets the type of the provider error policy that implements <see cref="ILwxProviderErrorPolicy"/>.
        /// Defaults to <see cref="LwxDefaultProviderErrorPolicy"/> which logs and continues.
        /// </summary>
        public Type? ProviderErrorPolicy { get; set; }

        /// <summary>
        /// Gets or sets a short summary of the handler's purpose, used for documentation.
        /// </summary>
        public string Summary { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets a detailed description of the handler's behavior.
        /// </summary>
        public string Description { get; set; } = string.Empty;

        /// <summary>
        /// Optional: provide a justification when a handler class name does not match the
        /// generator's expected naming convention. When present, the generator will accept
        /// the exception and skip the naming diagnostic.
        /// </summary>
        public string NamingExceptionJustification { get; set; } = string.Empty;

        /// <summary>
        /// Initializes a new instance of the <see cref="LwxMessageHandlerAttribute"/> class.
        /// </summary>
        public LwxMessageHandlerAttribute() { }

        /// <summary>
        /// Initializes a new instance of the <see cref="LwxMessageHandlerAttribute"/> class
        /// with the specified URI.
        /// </summary>
        /// <param name="uri">The URI pattern for the optional HTTP endpoint.</param>
        public LwxMessageHandlerAttribute(string uri)
        {
            Uri = uri;
        }
    }
}
