// <auto-generated/>
#nullable enable
using System;

namespace Lwx.Builders.MicroService.Atributtes
{
    /// <summary>
    /// Descriptor describing a generated message handler instance and metadata for health checks and monitoring.
    /// </summary>
    public sealed class LwxMessageHandlerDescriptor
    {
        /// <summary>
        /// Human-friendly name for the message handler.
        /// </summary>
        public string Name { get; init; } = string.Empty;

        /// <summary>
        /// Description of the message handler's purpose.
        /// </summary>
        public string Description { get; init; } = string.Empty;

        /// <summary>
        /// Number of concurrent readers/processors.
        /// </summary>
        public int QueueReaders { get; init; }

        /// <summary>
        /// Configuration section name for the queue provider.
        /// </summary>
        public string QueueConfigSection { get; init; } = string.Empty;

        /// <summary>
        /// Type of the queue provider.
        /// </summary>
        public Type? QueueProviderType { get; init; }

        /// <summary>
        /// Optional HTTP URI if the handler also exposes an HTTP endpoint.
        /// </summary>
        public string? HttpUri { get; init; }
    }
}
