// <auto-generated/>
#nullable enable
using System;

namespace Lwx.Builders.MicroService.Atributtes;

/// <summary>
/// Marks an endpoint method as also receiving messages from a queue source.
/// Use together with <see cref="LwxEndpointAttribute"/> to define an endpoint
/// that can be triggered both via HTTP and via queue messages.
/// </summary>
/// <remarks>
/// <para>The endpoint's <c>Execute</c> method must accept an <see cref="ILwxQueueMessage"/>
/// parameter as its first parameter when this attribute is present.</para>
/// <para>Example usage:</para>
/// <code>
/// public partial class EndpointMsgReceiveOrder
/// {
///     [LwxEndpoint("POST /receive-order", Publish = LwxStage.DevelopmentOnly)]
///     [LwxMessageSource(
///         QueueProvider = typeof(MyQueueProvider),
///         QueueConfigSection = "OrderQueue",
///         QueueReaders = 2,
///         Stage = LwxStage.All
///     )]
///     public static Task Execute(ILwxQueueMessage msg, ILogger logger) { /* ... */ }
/// }
/// </code>
/// </remarks>
[AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
public class LwxMessageSourceAttribute : Attribute
{
    /// <summary>
    /// Gets or sets the deployment stage(s) where the queue consumer should be active.
    /// Defaults to <see cref="LwxStage.None"/>, meaning the queue consumer is not active.
    /// </summary>
    public LwxStage Stage { get; set; } = LwxStage.None;

    /// <summary>
    /// Gets or sets the type of the queue provider that implements <see cref="ILwxQueueProvider"/>.
    /// </summary>
    public Type? QueueProvider { get; set; }

    /// <summary>
    /// Gets or sets the configuration section name for the queue provider.
    /// This corresponds to the "Queues:{SectionName}" path in appsettings.json.
    /// </summary>
    public string QueueConfigSection { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the number of concurrent readers/processors for the queue.
    /// Defaults to 2. Can be overridden by the provider's configuration.
    /// </summary>
    public int QueueReaders { get; set; } = 2;

    /// <summary>
    /// Gets or sets the type of the handler error policy that implements <see cref="ILwxErrorPolicy"/>.
    /// Defaults to <see cref="LwxDefaultErrorPolicy"/> which dead-letters messages on error.
    /// </summary>
    public Type? HandlerErrorPolicy { get; set; }

    /// <summary>
    /// Gets or sets the type of the provider error policy that implements <see cref="ILwxProviderErrorPolicy"/>.
    /// Defaults to <see cref="LwxDefaultProviderErrorPolicy"/> which logs and continues.
    /// </summary>
    public Type? ProviderErrorPolicy { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="LwxMessageSourceAttribute"/> class.
    /// </summary>
    public LwxMessageSourceAttribute() { }
}
