// <auto-generated/>
#nullable enable
using System;

namespace Lwx.Builders.MicroService.Atributtes
{
    /// <summary>
    /// Runtime descriptor for a message endpoint, providing metadata for health checks and monitoring.
    /// </summary>
    public sealed class LwxMessageEndpointDescriptor
    {
        /// <summary>
        /// Gets or sets the name of the message endpoint.
        /// </summary>
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets a description of the message endpoint.
        /// </summary>
        public string Description { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the number of concurrent queue readers.
        /// </summary>
        public int QueueReaders { get; set; }

        /// <summary>
        /// Gets or sets the configuration section name for the queue.
        /// </summary>
        public string QueueConfigSection { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the type of the queue provider.
        /// </summary>
        public Type? QueueProviderType { get; set; }

        /// <summary>
        /// Gets or sets the HTTP URI for direct message injection (if configured).
        /// </summary>
        public string? HttpUri { get; set; }

        /// <summary>
        /// Gets or sets whether the queue consumer is active.
        /// </summary>
        public bool QueueActive { get; set; }

        /// <summary>
        /// Gets or sets whether the HTTP endpoint is active.
        /// </summary>
        public bool HttpActive { get; set; }
    }
}
