// <auto-generated/>
#nullable enable
using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

namespace Lwx.Builders.MicroService.Atributtes
{
    /// <summary>
    /// Default implementation of <see cref="ILwxQueueMessage"/> for HTTP request body deserialization.
    /// Use this class as the <c>ReqBodyType</c> on <c>[LwxEndpoint]</c> when combined with <c>[LwxMessageSource]</c>.
    /// </summary>
    /// <remarks>
    /// <para>This class provides JSON-serializable properties for HTTP model binding while implementing
    /// the <see cref="ILwxQueueMessage"/> interface required by queue message handlers.</para>
    /// <para>The lifecycle methods (<see cref="CompleteAsync"/>, <see cref="AbandonAsync"/>, <see cref="DeadLetterAsync"/>)
    /// are no-op implementations since HTTP requests don't require queue acknowledgment.</para>
    /// <para>Example usage:</para>
    /// <code>
    /// [LwxEndpoint("POST /receive-order", Publish = LwxStage.DevelopmentOnly, ReqBodyType = typeof(LwxQueueMessage))]
    /// [LwxMessageSource(Stage = LwxStage.All, QueueProvider = typeof(MyQueueProvider), QueueConfigSection = "OrderQueue")]
    /// public static Task Execute(ILwxQueueMessage msg) => Task.CompletedTask;
    /// </code>
    /// </remarks>
    public class LwxQueueMessage : ILwxQueueMessage
    {
        /// <summary>
        /// Unique identifier for the message.
        /// </summary>
        [JsonPropertyName("messageId")]
        public string MessageId { get; set; } = Guid.NewGuid().ToString("N");

        /// <summary>
        /// The message payload as a string (typically JSON content).
        /// This property is used for JSON serialization/deserialization.
        /// </summary>
        [JsonPropertyName("payload")]
        public string PayloadString { get; set; } = string.Empty;

        /// <summary>
        /// The raw message payload as bytes (UTF-8 encoded from <see cref="PayloadString"/>).
        /// This property is ignored during JSON serialization.
        /// </summary>
        [JsonIgnore]
        public ReadOnlyMemory<byte> Payload => Encoding.UTF8.GetBytes(PayloadString);

        /// <summary>
        /// Message headers/properties as a mutable dictionary.
        /// This property is used for JSON serialization/deserialization.
        /// </summary>
        [JsonPropertyName("headers")]
        public Dictionary<string, string> HeadersDict { get; set; } = new();

        /// <summary>
        /// Message headers as a read-only dictionary (view of <see cref="HeadersDict"/>).
        /// This property is ignored during JSON serialization.
        /// </summary>
        [JsonIgnore]
        public IReadOnlyDictionary<string, string> Headers => HeadersDict;

        /// <summary>
        /// Timestamp when the message was enqueued.
        /// Defaults to the current UTC time for HTTP requests.
        /// </summary>
        [JsonPropertyName("enqueuedAt")]
        public DateTimeOffset EnqueuedAt { get; set; } = DateTimeOffset.UtcNow;

        /// <summary>
        /// Marks the message as successfully processed.
        /// No-op for HTTP requests since there's no queue to acknowledge.
        /// </summary>
        /// <param name="ct">Cancellation token (ignored).</param>
        /// <returns>A completed <see cref="ValueTask"/>.</returns>
        public ValueTask CompleteAsync(CancellationToken ct = default) => ValueTask.CompletedTask;

        /// <summary>
        /// Abandons the message, making it available for reprocessing.
        /// No-op for HTTP requests since there's no queue to abandon.
        /// </summary>
        /// <param name="reason">Optional reason for abandoning (ignored).</param>
        /// <param name="ct">Cancellation token (ignored).</param>
        /// <returns>A completed <see cref="ValueTask"/>.</returns>
        public ValueTask AbandonAsync(string? reason = null, CancellationToken ct = default) => ValueTask.CompletedTask;

        /// <summary>
        /// Moves the message to the dead-letter queue.
        /// No-op for HTTP requests since there's no queue to dead-letter.
        /// </summary>
        /// <param name="reason">Optional reason for dead-lettering (ignored).</param>
        /// <param name="ct">Cancellation token (ignored).</param>
        /// <returns>A completed <see cref="ValueTask"/>.</returns>
        public ValueTask DeadLetterAsync(string? reason = null, CancellationToken ct = default) => ValueTask.CompletedTask;
    }
}
