// <auto-generated/>
using System;

namespace Lwx.Builders.MicroService.Atributes
{
    /// <summary>
    /// Marks a class as the microservice descriptor. This attribute contains metadata
    /// about the service (title, description, version and publish stage for Swagger via PublishSwagger) and is used
    /// by the generator to produce runtime wiring for swagger/openapi and related features.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
    public class LwxServiceConfigAttribute : Attribute
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public string Version { get; set; }
        public LwxStage PublishSwagger { get; set; } = LwxStage.None;
        // GenerateMain flag removed — generator no longer emits a Main method.

        public LwxServiceConfigAttribute() { }
    }
}