// <auto-generated/>
using System;

namespace Lwx.Builders.MicroService.Atributtes
{
    /// <summary>
    /// Marks a static partial property as sourced from application configuration.
    /// The value will be read from the configuration using the specified key path
    /// (e.g., "Section:SubSection:Key") during Service.Configure(WebApplicationBuilder).
    /// Only primitive types (string, int, bool, double, long, float, decimal) are supported.
    /// </summary>
    /// <example>
    /// <code>
    /// public partial class MyEndpoint
    /// {
    ///     [LwxSetting("Database:ConnectionString")]
    ///     public static partial string ConnectionString { get; }
    ///     
    ///     [LwxSetting("App:MaxRetries")]
    ///     public static partial int MaxRetries { get; }
    /// }
    /// </code>
    /// </example>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
    public sealed class LwxSettingAttribute : Attribute
    {
        /// <summary>
        /// The configuration key path. Use ':' as separator for nested sections
        /// (e.g., "Section:SubSection:Key").
        /// </summary>
        public string Key { get; }

        /// <summary>
        /// Creates a new instance of the LwxSettingAttribute.
        /// </summary>
        /// <param name="key">The configuration key path.</param>
        public LwxSettingAttribute(string key)
        {
            Key = key ?? string.Empty;
        }
    }
}
