// <auto-generated/>
namespace Lwx.Builders.MicroService.Atributtes
{
    /// <summary>
    /// Defines the deployment stages for Lwx endpoints and services.
    /// This enum controls when endpoints are active based on the application's environment.
    /// </summary>
    public enum LwxStage
    {
        /// <summary>
        /// The endpoint or service is disabled and will not be mapped.
        /// </summary>
        None = 0,

        /// <summary>
        /// The endpoint or service is active only in development environments.
        /// </summary>
        DevelopmentOnly = 1,

        /// <summary>
        /// The endpoint or service is active in all deployment environments.
        /// </summary>
        All = 2
    }
}