// <auto-generated/>
#nullable enable
using System;

namespace Lwx.Builders.MicroService.Atributtes;

/// <summary>
/// Marks an endpoint class as a timer-triggered endpoint that executes on a schedule.
/// </summary>
/// <remarks>
/// <para>The timer endpoint class should have a static <c>Execute</c> method that will be
/// called according to the cron schedule. DI parameters are supported.</para>
/// <para>Example usage:</para>
/// <code>
/// public partial class EndpointTimerCleanup
/// {
///     [LwxTimer(
///         CronExpression = "0 */5 * * * *",   // Every 5 minutes
///         Stage = LwxStage.All,
///         Summary = "Cleanup timer"
///     )]
///     public static async Task Execute(ILogger&lt;EndpointTimerCleanup&gt; logger)
///     {
///         logger.LogInformation("Timer executed at {Time}", DateTimeOffset.Now);
///     }
/// }
/// </code>
/// </remarks>
[AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
public class LwxTimerAttribute : Attribute
{
    /// <summary>
    /// Gets or sets the cron expression that defines the timer schedule.
    /// Uses NCrontab 6-field format: "second minute hour day month weekday".
    /// Examples:
    /// - "0 */5 * * * *" = Every 5 minutes
    /// - "0 0 * * * *" = Every hour
    /// - "0 0 0 * * *" = Every day at midnight
    /// - "0 30 9 * * 1-5" = Weekdays at 9:30 AM
    /// Note: If IntervalSeconds is set, it takes precedence over CronExpression.
    /// </summary>
    public string CronExpression { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the interval in seconds between timer executions.
    /// If set to a value greater than 0, the timer will use a simple interval-based
    /// schedule instead of a cron expression.
    /// </summary>
    public int IntervalSeconds { get; set; } = 0;

    /// <summary>
    /// Gets or sets the deployment stage(s) where the timer should be active.
    /// Defaults to <see cref="LwxStage.All"/>.
    /// </summary>
    public LwxStage Stage { get; set; } = LwxStage.All;

    /// <summary>
    /// Gets or sets whether to run the timer immediately on application startup.
    /// Defaults to false.
    /// </summary>
    public bool RunOnStartup { get; set; } = false;

    /// <summary>
    /// Gets or sets a short summary of the timer's purpose, used for documentation.
    /// </summary>
    public string Summary { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets a detailed description of the timer's behavior.
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Optional: provide a justification when a timer class name does not match the
    /// generator's expected naming convention.
    /// </summary>
    public string NamingExceptionJustification { get; set; } = string.Empty;

    /// <summary>
    /// Initializes a new instance of the <see cref="LwxTimerAttribute"/> class.
    /// </summary>
    public LwxTimerAttribute() { }

    /// <summary>
    /// Initializes a new instance with a cron expression.
    /// </summary>
    /// <param name="cronExpression">The cron expression for the timer schedule.</param>
    public LwxTimerAttribute(string cronExpression)
    {
        CronExpression = cronExpression;
    }
}

/// <summary>
/// Descriptor for a timer endpoint, registered at runtime for health/monitoring.
/// </summary>
public class LwxTimerDescriptor
{
    /// <summary>
    /// Gets or sets the timer endpoint name.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the cron expression.
    /// </summary>
    public string CronExpression { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the timer description.
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets whether the timer runs on startup.
    /// </summary>
    public bool RunOnStartup { get; set; }

    /// <summary>
    /// Gets or sets the last execution time.
    /// </summary>
    public DateTimeOffset? LastExecutionTime { get; set; }

    /// <summary>
    /// Gets or sets the next scheduled execution time.
    /// </summary>
    public DateTimeOffset? NextExecutionTime { get; set; }
}
