// <auto-generated/>
namespace Lwx.Builders.MicroService.Atributtes
{
    /// <summary>
    /// Descriptor describing a generated worker instance and hints for health checks and orchestration.
    /// </summary>
    public sealed class LwxWorkerDescriptor
    {
        public string Name { get; init; } = string.Empty;
        public string Description { get; init; } = string.Empty;
        public int Threads { get; init; }
        public LwxWorkerPolicy Policy { get; init; } = LwxWorkerPolicy.AlwaysHealthy;
    }
}
