// <auto-generated/>
namespace Lwx.Builders.MicroService.Atributtes
{
    /// <summary>
    /// Defines the supported worker health policies for Lwx workers.
    /// </summary>
    public enum LwxWorkerPolicy
    {
        /// <summary>
        /// Treat the worker as healthy unless it exits unexpectedly.
        /// </summary>
        UnhealthyIfExit = 0,

        /// <summary>
        /// Treat the worker as unhealthy if an exception is observed.
        /// </summary>
        UnhealthyOnException = 1,

        /// <summary>
        /// Always report the worker as healthy (no automatic failure detection).
        /// </summary>
        AlwaysHealthy = 2
    }
}
