// <auto-generated/>
using System;

namespace Lwx.Builders.MicroService.Atributes
{
    /// <summary>
    /// Marks a class as an Lwx worker service, enabling automatic registration
    /// as a background service in the dependency injection container.
    /// </summary>
    /// <remarks>
    /// <para>The worker class must implement <see cref="Microsoft.Extensions.Hosting.BackgroundService"/>
    /// or <see cref="System.Threading.Tasks.Task"/> based execution patterns.</para>
    /// <para>The source generator will create the necessary service registrations
    /// to integrate the worker into the application's hosting lifecycle.</para>
    /// <para>Example usage:</para>
    /// <code>
    /// [LwxWorker]
    /// public class DataProcessorWorker : BackgroundService
    /// {
    ///     protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    ///     {
    ///         // Worker implementation
    ///     }
    /// }
    /// </code>
    /// </remarks>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
    public class LwxWorkerAttribute : Attribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LwxWorkerAttribute"/> class.
        /// </summary>
        public LwxWorkerAttribute() { }

        /// <summary>
        /// Optional: a human-friendly name for the worker. Defaults to the class name when not provided.
        /// </summary>
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Optional: description for the worker. Helpful for documentation or configuration samples.
        /// </summary>
        public string Description { get; set; } = string.Empty;

        /// <summary>
        /// Optional: number of threads / instances desired for the worker. Defaults to 2.
        /// </summary>
        public int Threads { get; set; } = 2;

        /// <summary>
        /// Health policy for the worker — controls how the platform treats worker failures.
        /// </summary>
        public LwxWorkerPolicy Policy { get; set; } = LwxWorkerPolicy.AlwaysHealthy;

        /// <summary>
        /// The stage in which this worker should run (Development/Production/None).
        /// Defaults to None (disabled) so projects must explicitly opt-in.
        /// </summary>
        public LwxStage Stage { get; set; } = LwxStage.None;
    }
}