using Microsoft.CodeAnalysis;
using Lwx.Builders.MicroService;

namespace Lwx.Builders.MicroService.Processors;

internal class LwxEventHubConsumerTypeProcessor(
    Generator parent,
    Compilation compilation,
    SourceProductionContext ctx,
    FoundAttribute attr
)
{
    public void Execute()
    {
        // enforce file path and namespace matching for classes marked with Lwx attributes
        GeneratorHelpers.ValidateFilePathMatchesNamespace(attr.TargetSymbol, ctx);
        var name = GeneratorHelpers.SafeIdentifier(attr.TargetSymbol.Name);
        var ns = attr.TargetSymbol.ContainingNamespace?.ToDisplayString() ?? "Generated";
        var source = $$"""
            // <auto-generated/>
            namespace {{ns}};

            public static partial class LwxEventHubConsumer_Generated_{{name}}
            {
                // Detected attribute: {{attr.AttributeName}} on {{attr.TargetSymbol.Kind}} {{attr.TargetSymbol.Name}}
            }
            """;

        GeneratorHelpers.AddGeneratedFile(ctx, $"LwxEventHubConsumer_{name}.g.cs", source);
    }
}
