// <auto-generated/>
using System;

namespace Lwx.Archetype.MicroService.Atributes
{
    /// <summary>
    /// Marks a class as a Data Transfer Object (DTO) for Lwx microservices.
    /// This attribute enables the source generator to recognize and potentially
    /// generate additional code or validations for DTO classes.
    /// </summary>
    /// <remarks>
    /// <para>DTOs marked with this attribute are typically used for request/response
    /// models in API endpoints and can benefit from automatic serialization handling.</para>
    /// <para>Example usage:</para>
    /// <code>
    /// [LwxDto]
    /// public class UserDto
    /// {
    ///     public int Id { get; set; }
    ///     public string Name { get; set; }
    /// </code>
    /// </remarks>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
    public class LwxDtoAttribute : Attribute
    {
        /// <summary>
        /// Gets or sets the implementation type for the DTO properties.
        /// </summary>
        public DtoType Type { get; set; } = DtoType.Normal;

        /// <summary>
        /// Initializes a new instance of the <see cref="LwxDtoAttribute"/> class.
        /// </summary>
        public LwxDtoAttribute() { }

        /// <summary>
        /// Initializes a new instance of the <see cref="LwxDtoAttribute"/> class with the specified type.
        /// </summary>
        /// <param name="type">The implementation type for the DTO.</param>
        public LwxDtoAttribute(DtoType type)
        {
            Type = type;
        }
    }
}