// <auto-generated/>
using System;

namespace Lwx.Archetype.MicroService.Atributes
{
    /// <summary>
    /// Marks a class for Swagger/OpenAPI documentation generation.
    /// This attribute enables automatic configuration of Swagger services
    /// with the specified API metadata.
    /// </summary>
    /// <remarks>
    /// <para>The swagger configuration will be added to the service collection
    /// when the application starts, providing API documentation.</para>
    /// <para>Example usage:</para>
    /// <code>
    /// [LwxSwagger(
    ///     Title = "My API",
    ///     Description = "API description",
    ///     Version = "v1.0.0",
    ///     Publish = LwxStage.Development
    /// )]
    /// public class SwaggerConfig { }
    /// </code>
    /// </remarks>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
    public class LwxSwaggerAttribute : Attribute
    {
        /// <summary>
        /// Gets or sets the title of the API.
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// Gets or sets the description of the API.
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets the version of the API.
        /// </summary>
        public string Version { get; set; }

        /// <summary>
        /// Gets or sets the deployment stage(s) where Swagger should be enabled.
        /// Defaults to <see cref="LwxStage.None"/>, meaning Swagger is disabled.
        /// </summary>
        public LwxStage Publish { get; set; } = LwxStage.None;

        /// <summary>
        /// Initializes a new instance of the <see cref="LwxSwaggerAttribute"/> class.
        /// </summary>
        public LwxSwaggerAttribute() { }
    }
}