// <auto-generated/>
using System;

namespace Lwx.Archetype.MicroService.Atributes
{
    /// <summary>
    /// Marks a class as an Azure Service Bus message producer, enabling automatic
    /// registration of message sending capabilities for Service Bus queues or topics.
    /// </summary>
    /// <remarks>
    /// <para>The producer class should implement methods to send messages to
    /// Azure Service Bus.</para>
    /// <para>The source generator will create the necessary Azure Service Bus client
    /// registrations and message sending infrastructure.</para>
    /// <para>Example usage:</para>
    /// <code>
    /// [LwxServiceBusProducer]
    /// public class OrderPublisher
    /// {
    ///     public static async Task SendOrderAsync(Order order)
    ///     {
    ///         // Message sending logic
    ///     }
    /// }
    /// </code>
    /// </remarks>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
    public class LwxServiceBusProducerAttribute : Attribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LwxServiceBusProducerAttribute"/> class.
        /// </summary>
        public LwxServiceBusProducerAttribute() { }
    }
}