// <auto-generated/>
using System;

namespace Lwx.Archetype.MicroService.Atributes
{
    /// <summary>
    /// Marks a class as an Lwx worker service, enabling automatic registration
    /// as a background service in the dependency injection container.
    /// </summary>
    /// <remarks>
    /// <para>The worker class must implement <see cref="Microsoft.Extensions.Hosting.BackgroundService"/>
    /// or <see cref="System.Threading.Tasks.Task"/> based execution patterns.</para>
    /// <para>The source generator will create the necessary service registrations
    /// to integrate the worker into the application's hosting lifecycle.</para>
    /// <para>Example usage:</para>
    /// <code>
    /// [LwxWorker]
    /// public class DataProcessorWorker : BackgroundService
    /// {
    ///     protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    ///     {
    ///         // Worker implementation
    ///     }
    /// }
    /// </code>
    /// </remarks>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
    public class LwxWorkerAttribute : Attribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LwxWorkerAttribute"/> class.
        /// </summary>
        public LwxWorkerAttribute() { }
    }
}