// <auto-generated/>
#nullable enable
using System;
using System.Text.Json.Serialization;

namespace Lwx.MicroService.Atributes
{
    /// <summary>
    /// Marks a property in a DTO class for special JSON serialization handling.
    /// This attribute enables customization of JSON property names, converters, and other serialization behaviors.
    /// </summary>
    /// <remarks>
    /// <para>This attribute is used on partial properties in classes marked with <see cref="LwxDtoAttribute"/>.</para>
    /// <para>Example usage:</para>
    /// <code>
    /// [LwxDtoProperty(JsonName = "user-name")]
    /// public partial string? UserName { get; set; }
    /// </code>
    /// </remarks>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
    public class LwxDtoPropertyAttribute : Attribute
    {
        /// <summary>
        /// Gets or sets the JSON property name to use for serialization.
        /// If not specified, the property name is used.
        /// </summary>
        public required string JsonName { get; set; }

        /// <summary>
        /// Gets or sets the type of JSON converter to use for serialization.
        /// </summary>
        public Type? JsonConverter { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="LwxDtoPropertyAttribute"/> class.
        /// </summary>
        public LwxDtoPropertyAttribute() { }
    }
}