// <auto-generated/>
using System;

namespace Lwx.MicroService.Atributes
{
    /// <summary>
    /// Marks a class as an Azure Service Bus message consumer, enabling automatic
    /// registration of message handlers for Service Bus queues or topics.
    /// </summary>
    /// <remarks>
    /// <para>The consumer class should implement methods to process incoming messages
    /// from Azure Service Bus.</para>
    /// <para>The source generator will create the necessary Azure Service Bus client
    /// registrations and message processing infrastructure.</para>
    /// <para>Example usage:</para>
    /// <code>
    /// [LwxServiceBusConsumer]
    /// public class OrderProcessor
    /// {
    ///     public static async Task ProcessMessageAsync(OrderMessage message)
    ///     {
    ///         // Message processing logic
    ///     }
    /// }
    /// </code>
    /// </remarks>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
    public class LwxServiceBusConsumerAttribute : Attribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LwxServiceBusConsumerAttribute"/> class.
        /// </summary>
        public LwxServiceBusConsumerAttribute() { }
    }
}