// <auto-generated/>
using System;

namespace Lwx.MicroService.Atributes
{
    /// <summary>
    /// Marks a class as an Lwx timer-triggered service, enabling automatic
    /// registration of timer-based background tasks.
    /// </summary>
    /// <remarks>
    /// <para>The timer class should implement logic for periodic execution based on
    /// time intervals or cron expressions.</para>
    /// <para>The source generator will create the necessary infrastructure to
    /// schedule and execute the timer-based operations.</para>
    /// <para>Example usage:</para>
    /// <code>
    /// [LwxTimer]
    /// public class CleanupTimer
    /// {
    ///     public static async Task ExecuteAsync()
    ///     {
    ///         // Periodic cleanup logic
    ///     }
    /// }
    /// </code>
    /// </remarks>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
    public class LwxTimerAttribute : Attribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LwxTimerAttribute"/> class.
        /// </summary>
        public LwxTimerAttribute() { }
    }
}